name = "pcr-oc-2026jun"
pages_build_output_dir = "public"
compatibility_date = "2026-06-21"

[[kv_namespaces]]
binding = "WATCHLISTS"
id = "36d79cf423fd4bb9bdd93253938686bf"
preview_id = "ae489214ea7646a5aaa140c1665381a7"
